### ISSUE TITLE
Installing go-fuzz - issue

### ISSUE THREAD

**Issue by tomercagan** [thepudds/fzgo#21]
Hi,

First off - cool project - I was looking around to doing something similar and then found it... especially interested in genfuzzfunc script.

As for the issue - when installing go-fuzz as specified in the readme, i.e.

```bash
go get -u github.com/dvyukov/go-fuzz/...
```

I am getting an error (quite consistently):

```console
root@fd9d5ec3cb0a:/go# go get -u github.com/dvyukov/go-fuzz/...
go: downloading github.com/dvyukov/go-fuzz v0.0.0-20210429054444-fca39067bc72
go: downloading github.com/stephens2424/writerset v1.0.2
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.1
go: downloading golang.org/x/mod v0.3.0
github.com/dvyukov/go-fuzz/test imports
	non.existent.com/foo: cannot find module providing package non.existent.com/foo
```

As [per this (old) issue](https://github.com/dvyukov/go-fuzz/issues/235), it is better to explicitly install go-fuzz and go-fuzz-build, i.e.:

```bash
go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build
```

Which works just fine...

I am not sure whether this is something I face because of some versions/environment - but if not - maybe it is worth updating the readme (assuming this project is still active)

**Comment by thepudds** [comment]
Hi @tomercagan,

First of all, thank you for the issue here, and sorry for the delayed response.

>  cool project - I was looking around to doing something similar and then found it... especially interested in genfuzzfunc script.

In terms of genfuzzfunc piece of this, I have continued that work in a successor project https://github.com/thepudds.fzgen.

FWIW, I primarily intended fzgo to serve as a prototype for first class fuzzing in cmd/go. It did help with that from what I could see.

On the other hand, I intend to bring fzgen to 1.0.0 status and have it be more generally useful than just a prototype.

Here is a short summary of fzgen as it stands now:

   * auto-gen fuzzing wrappers for Go 1.18.
   * can automatically find problematic call sequences, with the sequence & args under the control of the fuzzer.
   * can automatically wire outputs to inputs and reuse input args across API calls.
   * can emit a valid chunk of Go code as a reproducer for a given crasher (currently best effort).
   * supports rich types (e.g, structs, maps, some common interfaces like io.Reader, etc.), even with Go 1.18.

The [README](https://github.com/thepudds/fzgen#example-easily-finding-a-data-race) there has some examples, including automatically finding a data race and a deadlock without needing to write any code.

Thanks again.
